// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class EvaluationType
{
    public int EvaluationTypeId { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<PlayerEvaluationDetail> PlayerEvaluationDetails { get; set; } = new List<PlayerEvaluationDetail>();
}