// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Gender
{
    public int GenderId { get; set; }

    public string GenderName { get; set; }

    public virtual ICollection<Player> Players { get; set; } = new List<Player>();
}