// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class ManagerTrainerAssignment
{
    public int ManagerTrainerAssignmentId { get; set; }

    public int ManagerId { get; set; }

    public int TrainerId { get; set; }

    public DateTime JoiningDate { get; set; }

    public virtual Manager Manager { get; set; }

    public virtual Trainer Trainer { get; set; }
}
