// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Manager
{
    
    public int ManagerId { get; set; }

    public string Name { get; set; }

    public DateTime Dob { get; set; }

    public string ImageUrl { get; set; }

    public string ContactNumber { get; set; }

    public string Email { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<ManagerTrainerAssignment> ManagerTrainerAssignments { get; set; } = new List<ManagerTrainerAssignment>();
}