// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class MatchFormat
{
    public int MatchFormatId { get; set; }

    public string FormatName { get; set; }

    public virtual ICollection<Match> Matches { get; set; } = new List<Match>();
}