// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Match
{
    public int MatchId { get; set; }

    public string Title { get; set; }

    public DateTime MatchDate { get; set; }

    public string Venue { get; set; }

    public string TeamA { get; set; }

    public string TeamB { get; set; }

    public string Result { get; set; }

    public int MatchFormatId { get; set; }

    public virtual MatchFormat MatchFormat { get; set; }

    public virtual ICollection<PlayerEvaluationDetail> PlayerEvaluationDetails { get; set; } = new List<PlayerEvaluationDetail>();
}