// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Player
{
    public int PlayerId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateTime? DateOfBirth { get; set; }

    public string FathersName { get; set; }

    public string MothersName { get; set; }

    public string MobileNo { get; set; }

    public string ImageUrl { get; set; }

    public string ImageName { get; set; }

    public string NidNumber { get; set; }

    public string Email { get; set; }

    public decimal? Height { get; set; }

    public decimal? PlayerWeight { get; set; }

    public string LastEducationalQualification { get; set; }

    public int SportsTypeId { get; set; }

    public int BloodGroupId { get; set; }

    public int ReligionId { get; set; }

    public int GenderId { get; set; }

    public bool IsDeleted { get; set; }

    public virtual BloodGroup BloodGroup { get; set; }

    public virtual Gender Gender { get; set; }

    public virtual ICollection<PlayerEvaluation> PlayerEvaluations { get; set; } = new List<PlayerEvaluation>();

    public virtual ICollection<PlayerTrainingAssignment> PlayerTrainingAssignments { get; set; } = new List<PlayerTrainingAssignment>();

    public virtual Religion Religion { get; set; }

    public virtual SportsType SportsType { get; set; }
}