// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class PlayerTrainingAssignment
{
    public int PlayerTrainingAssignmentId { get; set; }

    public int PlayerId { get; set; }

    public int TrainingId { get; set; }

    public DateTime? TrainingDate { get; set; }

    public int Duration { get; set; }

    public string Venue { get; set; }

    public virtual Player Player { get; set; }

    public virtual Training Training { get; set; }
}