// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class PlayerEvaluation
{
    public int PlayerEvaluationId { get; set; }

    public int PlayerId { get; set; }

    public int TrainerId { get; set; }

    public DateTime EvaluationDate { get; set; }

    public bool IsCompleted { get; set; }

    public bool IsDeleted { get; set; }

    public string Remarks { get; set; }

    public virtual Player Player { get; set; }

    public virtual ICollection<PlayerEvaluationDetail> PlayerEvaluationDetails { get; set; } = new List<PlayerEvaluationDetail>();

    public virtual Trainer Trainer { get; set; }
}