// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class PlayerEvaluationDetail
{
    public int PlayerEvaluationDetailsId { get; set; }

    public int PlayerEvaluationId { get; set; }

    public int EvaluationTypeId { get; set; }

    public int? MatchId { get; set; }

    public int EvaluationCategoryId { get; set; }

    public int OverNumber { get; set; }

    public int? BallNumber { get; set; }

    public int? RunsScored { get; set; }

    public int? BallsFaced { get; set; }

    public int? Boundaries { get; set; }

    public bool? IsOut { get; set; }

    public string DismissalType { get; set; }

    public int? BallsBowled { get; set; }

    public int? RunsConceded { get; set; }

    public int? WicketsTaken { get; set; }

    public int? NoBalls { get; set; }

    public int? Wides { get; set; }

    public bool? IsBoundary { get; set; }

    public int? CatchesTaken { get; set; }

    public int? RunOuts { get; set; }

    public int? Misfields { get; set; }

    public int? Stumpings { get; set; }

    public virtual EvaluationCategory EvaluationCategory { get; set; }

    public virtual EvaluationType EvaluationType { get; set; }

    public virtual Match Match { get; set; }

    public virtual PlayerEvaluation PlayerEvaluation { get; set; }
}