// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Skill
{
    public int SkillId { get; set; }

    public string SkillName { get; set; }

    public virtual ICollection<TrainerSkill> TrainerSkills { get; set; } = new List<TrainerSkill>();
}