// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class SportsType
{
    public int SportsTypeId { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<Player> Players { get; set; } = new List<Player>();
}