// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Training
{
    public int TrainingId { get; set; }

    public string TrainingName { get; set; }

    public virtual ICollection<PlayerTrainingAssignment> PlayerTrainingAssignments { get; set; } = new List<PlayerTrainingAssignment>();
}