// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class Trainer
{
    public int TrainerId { get; set; }

    public string TrainerName { get; set; }

    public DateTime DateOfBirth { get; set; }

    public string MobileNo { get; set; }

    public string Email { get; set; }

    public string Picture { get; set; }

    public bool IsExperienced { get; set; }

    public virtual ICollection<ManagerTrainerAssignment> ManagerTrainerAssignments { get; set; } = new List<ManagerTrainerAssignment>();

    public virtual ICollection<PlayerEvaluation> PlayerEvaluations { get; set; } = new List<PlayerEvaluation>();

    public virtual ICollection<TrainerSkill> TrainerSkills { get; set; } = new List<TrainerSkill>();
}