// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PlayerManagement.Models;

public partial class TrainerSkill
{
    public int TrainerSkillId { get; set; }

    public int TrainerId { get; set; }

    public int SkillId { get; set; }

    public int Experience { get; set; }

    public virtual Skill Skill { get; set; }

    public virtual Trainer Trainer { get; set; }
}